/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_llnl_lc_chaos_Munge */

#ifndef _Included_gov_llnl_lc_chaos_Munge
#define _Included_gov_llnl_lc_chaos_Munge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_llnl_lc_chaos_Munge
 * Method:    munge_constructor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_llnl_lc_chaos_Munge_munge_1constructor
  (JNIEnv *, jobject);

/*
 * Class:     gov_llnl_lc_chaos_Munge
 * Method:    encode
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_gov_llnl_lc_chaos_Munge_encode
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     gov_llnl_lc_chaos_Munge
 * Method:    decode
 * Signature: ([B)Lgov/llnl/lc/chaos/MungeDecodeData;
 */
JNIEXPORT jobject JNICALL Java_gov_llnl_lc_chaos_Munge_decode
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     gov_llnl_lc_chaos_Munge
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gov_llnl_lc_chaos_Munge_cleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
